# Generated by Django 5.0.3 on 2024-03-07 13:50

from django.db import migrations
from django.conf import settings


def create_superuser(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)

    if not User.objects.filter(username=settings.ADMIN_NAME).exists():
        User.objects.create_superuser(
            settings.ADMIN_NAME,
            settings.ADMIN_EMAIL,
            settings.ADMIN_PASSWORD,
        ).save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]
