name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: 
      name: project
    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
    - name: Run Tests
      run: |
        python server/reminderAI/manage.py test
